/* ═══════════════════════════════════════════════════════════════════════════════
   MOCK RESTAURANTS - Sample restaurant data for development
   Used by marquee components and card examples
   ═══════════════════════════════════════════════════════════════════════════════ */

import type {
  PriceTier,
  ShadiBadge,
  ShadiRestaurant,
  ThemeCategory,
  UAEEmirate,
} from "@/types/restaurant"

// Re-export ShadiRestaurant type for convenience
export type { ShadiRestaurant, ShadiBadge } from "@/types/restaurant"

// Sample restaurant data for development
export const mockRestaurants: ShadiRestaurant[] = [
  {
    id: "1",
    slug: "al-bait-arabic",
    name: "Al Bait Arabic Kitchen",
    description: "Authentic Arabic cuisine with traditional recipes",
    image: "/images/restaurants/al-bait.jpg",
    images: ["/images/restaurants/al-bait.jpg"],
    rating: 4.8,
    reviewCount: 324,
    price: "$$",
    priceTier: "$$",
    theme: "arabic",
    location: { emirate: "dubai", district: "Downtown" },
    emirate: "dubai" as UAEEmirate,
    district: "Downtown",
    shadiBadges: ["verified", "popular"],
    verified: true,
    featured: true,
  },
  {
    id: "2",
    slug: "spice-garden-indian",
    name: "Spice Garden Indian",
    description: "Flavors of India in every bite",
    image: "/images/restaurants/spice-garden.jpg",
    images: ["/images/restaurants/spice-garden.jpg"],
    rating: 4.6,
    reviewCount: 256,
    price: "$$",
    priceTier: "$$",
    theme: "indian",
    location: { emirate: "dubai", district: "JBR" },
    emirate: "dubai" as UAEEmirate,
    district: "JBR",
    shadiBadges: ["spicy", "vegetarian-friendly"],
    verified: true,
  },
  {
    id: "3",
    slug: "le-pain-francais",
    name: "Le Pain Francais",
    description: "French bakery and cafe",
    image: "/images/restaurants/le-pain.jpg",
    images: ["/images/restaurants/le-pain.jpg"],
    rating: 4.5,
    reviewCount: 189,
    price: "$$$",
    priceTier: "$$$",
    theme: "french",
    location: { emirate: "abu_dhabi", district: "Corniche" },
    emirate: "abu_dhabi" as UAEEmirate,
    district: "Corniche",
    shadiBadges: ["breakfast", "coffee"],
    verified: true,
  },
  {
    id: "4",
    slug: "sakura-japanese",
    name: "Sakura Japanese",
    description: "Premium Japanese sushi and grill",
    image: "/images/restaurants/sakura.jpg",
    images: ["/images/restaurants/sakura.jpg"],
    rating: 4.9,
    reviewCount: 412,
    price: "$$$$",
    priceTier: "$$$$",
    theme: "japanese",
    location: { emirate: "dubai", district: "Marina" },
    emirate: "dubai" as UAEEmirate,
    district: "Marina",
    shadiBadges: ["sushi", "premium", "omakase"],
    verified: true,
    featured: true,
  },
  {
    id: "5",
    slug: "pasta-italia",
    name: "Pasta Italia",
    description: "Homemade pasta and Italian classics",
    image: "/images/restaurants/pasta-italia.jpg",
    images: ["/images/restaurants/pasta-italia.jpg"],
    rating: 4.4,
    reviewCount: 178,
    price: "$$",
    priceTier: "$$",
    theme: "italian",
    location: { emirate: "dubai", district: "Business Bay" },
    emirate: "dubai" as UAEEmirate,
    district: "Business Bay",
    shadiBadges: ["family-friendly"],
    verified: true,
  },
  {
    id: "6",
    slug: "thai-orchid",
    name: "Thai Orchid",
    description: "Authentic Thai street food",
    image: "/images/restaurants/thai-orchid.jpg",
    images: ["/images/restaurants/thai-orchid.jpg"],
    rating: 4.7,
    reviewCount: 267,
    price: "$$",
    priceTier: "$$",
    theme: "thai",
    location: { emirate: "sharjah", district: "Al Qasba" },
    emirate: "sharjah" as UAEEmirate,
    district: "Al Qasba",
    shadiBadges: ["spicy", "street-food"],
    verified: true,
  },
  {
    id: "7",
    slug: "mexican-fiesta",
    name: "Mexican Fiesta",
    description: "Tacos, burritos, and margaritas",
    image: "/images/restaurants/mexican-fiesta.jpg",
    images: ["/images/restaurants/mexican-fiesta.jpg"],
    rating: 4.3,
    reviewCount: 145,
    price: "$",
    priceTier: "$",
    theme: "mexican",
    location: { emirate: "dubai", district: "Karama" },
    emirate: "dubai" as UAEEmirate,
    district: "Karama",
    shadiBadges: ["casual", "happy-hour"],
    verified: true,
  },
  {
    id: "8",
    slug: "steakhouse-elite",
    name: "Steakhouse Elite",
    description: "Premium steaks and fine dining",
    image: "/images/restaurants/steakhouse.jpg",
    images: ["/images/restaurants/steakhouse.jpg"],
    rating: 4.8,
    reviewCount: 356,
    price: "$$$$",
    priceTier: "$$$$",
    theme: "steakhouse",
    location: { emirate: "dubai", district: "DIFC" },
    emirate: "dubai" as UAEEmirate,
    district: "DIFC",
    shadiBadges: ["premium", "fine-dining", "wine-selection"],
    verified: true,
    featured: true,
  },
  {
    id: "9",
    slug: "seafood-cove",
    name: "Seafood Cove",
    description: "Fresh catch of the day",
    image: "/images/restaurants/seafood-cove.jpg",
    images: ["/images/restaurants/seafood-cove.jpg"],
    rating: 4.6,
    reviewCount: 234,
    price: "$$$",
    priceTier: "$$$",
    theme: "seafood",
    location: { emirate: "dubai", district: "Jumeirah" },
    emirate: "dubai" as UAEEmirate,
    district: "Jumeirah",
    shadiBadges: ["fresh", "waterfront"],
    verified: true,
  },
  {
    id: "10",
    slug: "fusion-lab",
    name: "Fusion Lab",
    description: "Experimental fusion cuisine",
    image: "/images/restaurants/fusion-lab.jpg",
    images: ["/images/restaurants/fusion-lab.jpg"],
    rating: 4.5,
    reviewCount: 189,
    price: "$$$",
    priceTier: "$$$",
    theme: "fusion",
    location: { emirate: "dubai", district: "Alserkal" },
    emirate: "dubai" as UAEEmirate,
    district: "Alserkal",
    shadiBadges: ["innovative", "trending"],
    verified: true,
  },
  {
    id: "11",
    slug: "pakistani-delight",
    name: "Pakistani Delight",
    description: "Authentic Pakistani flavors",
    image: "/images/restaurants/pakistani.jpg",
    images: ["/images/restaurants/pakistani.jpg"],
    rating: 4.7,
    reviewCount: 298,
    price: "$",
    priceTier: "$",
    theme: "pakistani",
    location: { emirate: "dubai", district: "Karama" },
    emirate: "dubai" as UAEEmirate,
    district: "Karama",
    shadiBadges: ["halal", "spicy", "value"],
    verified: true,
  },
  {
    id: "12",
    slug: "persian-palace",
    name: "Persian Palace",
    description: "Traditional Persian keebabs and rice",
    image: "/images/restaurants/persian.jpg",
    images: ["/images/restaurants/persian.jpg"],
    rating: 4.6,
    reviewCount: 212,
    price: "$$",
    priceTier: "$$",
    theme: "persian",
    location: { emirate: "dubai", district: "Satwa" },
    emirate: "dubai" as UAEEmirate,
    district: "Satwa",
    shadiBadges: ["halal", "family-style"],
    verified: true,
  },
  // Add more restaurants to reach 25
  {
    id: "13",
    slug: "turkish-kitchen",
    name: "Turkish Kitchen",
    description: "Ottoman-inspired dishes",
    image: "/images/restaurants/turkish.jpg",
    images: ["/images/restaurants/turkish.jpg"],
    rating: 4.4,
    reviewCount: 156,
    price: "$$",
    priceTier: "$$",
    theme: "turkish",
    location: { emirate: "dubai", district: "Deira" },
    emirate: "dubai" as UAEEmirate,
    district: "Deira",
    shadiBadges: ["grill", "mezze"],
    verified: true,
  },
  {
    id: "14",
    slug: "cafe-bloom",
    name: "Cafe Bloom",
    description: "Artisan coffee and light bites",
    image: "/images/restaurants/cafe-bloom.jpg",
    images: ["/images/restaurants/cafe-bloom.jpg"],
    rating: 4.5,
    reviewCount: 189,
    price: "$",
    priceTier: "$",
    theme: "cafe",
    location: { emirate: "dubai", district: "Al Quoz" },
    emirate: "dubai" as UAEEmirate,
    district: "Al Quoz",
    shadiBadges: ["coffee", "brunch", "wifi"],
    verified: true,
  },
  {
    id: "15",
    slug: "sweet-dreams",
    name: "Sweet Dreams Bakery",
    description: "Artisan desserts and pastries",
    image: "/images/restaurants/bakery.jpg",
    images: ["/images/restaurants/bakery.jpg"],
    rating: 4.7,
    reviewCount: 234,
    price: "$$",
    priceTier: "$$",
    theme: "bakery",
    location: { emirate: "dubai", district: "JBR" },
    emirate: "dubai" as UAEEmirate,
    district: "JBR",
    shadiBadges: ["dessert", "fresh-baked"],
    verified: true,
  },
  // Additional restaurants to fill MARQUEE_ITEMS_2
  ...Array.from({ length: 10 }, (_, i) => {
    const priceTiers: PriceTier[] = ["$", "$$", "$$$", "$$$$"]
    const randomTier = priceTiers[Math.floor(Math.random() * 4)]
    return {
      id: `${16 + i}`,
      slug: `restaurant-${16 + i}`,
      name: `Restaurant ${16 + i}`,
      description: "Sample restaurant description",
      image: "/images/restaurants/placeholder.jpg",
      images: ["/images/restaurants/placeholder.jpg"],
      rating: 4.0 + Math.random() * 0.9,
      reviewCount: 100 + Math.floor(Math.random() * 200),
      price: randomTier,
      priceTier: randomTier,
      theme: "international" as ThemeCategory,
      location: { emirate: "dubai" as UAEEmirate, district: "Dubai" },
      emirate: "dubai" as UAEEmirate,
      district: "Dubai",
      shadiBadges: [] as string[],
      verified: Math.random() > 0.5,
    }
  }),
]

export default mockRestaurants
